//! TCP connection engine — per-flow control block.
//!
//! Manages the full lifecycle of a single TCP connection: handshake,
//! data transfer, and teardown. Processes incoming segments and
//! generates outgoing segments according to the RFC 793 state machine.
//!
//! Includes RFC 6298-compliant Retransmission Timeout (RTO) with
//! Jacobson/Karels RTT estimation and exponential backoff.

use crate::buffer::ring_buffer::RingBuffer;
use crate::error::{NetError, Result};
use crate::time::Instant;
use crate::wire::tcp::{self, flags, TcpPacket};
use super::state::TcpState;
use super::retransmit::{RtoEstimator, RetransmitQueue, RetransmitEntry, RetransmitResult};

/// Default window size advertised to the remote peer.
const DEFAULT_WINDOW: u16 = 65535;

/// Default buffer capacity (bytes) for send and receive.
const DEFAULT_BUFFER_CAP: usize = 65535;

/// A four-tuple identifying a TCP connection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ConnectionId {
    pub local_addr: [u8; 4],
    pub local_port: u16,
    pub remote_addr: [u8; 4],
    pub remote_port: u16,
}

/// A single TCP connection control block.
///
/// Tracks state, sequence numbers, send/receive buffers, and
/// retransmission state for one flow.
pub struct TcpConnection {
    /// Connection identifier (four-tuple).
    pub id: ConnectionId,
    /// Current TCP state.
    state: TcpState,
    /// Our send sequence number (next byte to send).
    send_next: u32,
    /// Initial send sequence number.
    send_isn: u32,
    /// Send unacknowledged (oldest unacknowledged byte).
    send_una: u32,
    /// Their receive sequence number (next byte we expect).
    recv_next: u32,
    /// Initial receive sequence number.
    recv_isn: u32,
    /// Send buffer (application data waiting to be sent).
    send_buffer: RingBuffer<u8>,
    /// Receive buffer (data received from peer, waiting for application).
    recv_buffer: RingBuffer<u8>,
    /// RTO estimator (Jacobson/Karels, RFC 6298).
    rto: RtoEstimator,
    /// Queue of in-flight segments awaiting acknowledgement.
    retransmit_queue: RetransmitQueue,
}

/// A segment generated by the connection engine to be sent out.
#[derive(Debug, Clone)]
pub struct TcpSegmentOut {
    pub src_port: u16,
    pub dst_port: u16,
    pub seq: u32,
    pub ack: u32,
    pub flags: u8,
    pub window: u16,
    pub payload: Vec<u8>,
}

impl TcpConnection {
    /// Create a new connection in the `Closed` state.
    pub fn new(id: ConnectionId) -> Self {
        TcpConnection {
            id,
            state: TcpState::Closed,
            send_next: 0,
            send_isn: 0,
            send_una: 0,
            recv_next: 0,
            recv_isn: 0,
            send_buffer: RingBuffer::new(DEFAULT_BUFFER_CAP),
            recv_buffer: RingBuffer::new(DEFAULT_BUFFER_CAP),
            rto: RtoEstimator::new(),
            retransmit_queue: RetransmitQueue::new(),
        }
    }

    /// Create a new connection with a specific buffer capacity.
    pub fn with_capacity(id: ConnectionId, capacity: usize) -> Self {
        TcpConnection {
            id,
            state: TcpState::Closed,
            send_next: 0,
            send_isn: 0,
            send_una: 0,
            recv_next: 0,
            recv_isn: 0,
            send_buffer: RingBuffer::new(capacity),
            recv_buffer: RingBuffer::new(capacity),
            rto: RtoEstimator::new(),
            retransmit_queue: RetransmitQueue::new(),
        }
    }

    /// Returns the current TCP state.
    pub fn state(&self) -> TcpState {
        self.state
    }

    /// Transition to a new state (validates the transition).
    fn transition(&mut self, next: TcpState) -> Result<()> {
        self.state.validate_transition(next)?;
        self.state = next;
        Ok(())
    }

    // ── Active open (client) ──────────────────────────────────────

    /// Initiate an active open (client connect).
    ///
    /// Generates a SYN segment. The ISN is provided by the caller
    /// (in production this comes from a secure ISN generator).
    /// The `now` timestamp is used to start the retransmission timer.
    pub fn connect(&mut self, isn: u32, now: Instant) -> Result<TcpSegmentOut> {
        self.transition(TcpState::SynSent)?;
        self.send_isn = isn;
        self.send_next = isn.wrapping_add(1); // SYN consumes one seq number
        self.send_una = isn;

        let seg = TcpSegmentOut {
            src_port: self.id.local_port,
            dst_port: self.id.remote_port,
            seq: isn,
            ack: 0,
            flags: flags::SYN,
            window: DEFAULT_WINDOW,
            payload: Vec::new(),
        };

        // Record the SYN for retransmission (SYN consumes 1 seq number).
        self.retransmit_queue.push(RetransmitEntry {
            seq_start: isn,
            seq_end: isn.wrapping_add(1),
            segment: seg.clone(),
            first_sent_at: now,
            last_sent_at: now,
            retransmit_count: 0,
        });

        Ok(seg)
    }

    // ── Passive open (server) ─────────────────────────────────────

    /// Enter the Listen state (passive open / server).
    pub fn listen(&mut self) -> Result<()> {
        self.transition(TcpState::Listen)
    }

    /// Accept an incoming SYN while in the Listen state.
    ///
    /// Generates a SYN-ACK segment. The `now` timestamp starts the
    /// retransmission timer for the SYN-ACK.
    pub fn accept(&mut self, syn_seg: &TcpPacket<&[u8]>, isn: u32, now: Instant) -> Result<TcpSegmentOut> {
        if self.state != TcpState::Listen {
            return Err(NetError::InvalidState);
        }
        if !syn_seg.syn() {
            return Err(NetError::InvalidHeader);
        }

        self.recv_isn = syn_seg.seq_number();
        self.recv_next = syn_seg.seq_number().wrapping_add(1);
        self.send_isn = isn;
        self.send_next = isn.wrapping_add(1);
        self.send_una = isn;

        self.transition(TcpState::SynReceived)?;

        let seg = TcpSegmentOut {
            src_port: self.id.local_port,
            dst_port: self.id.remote_port,
            seq: isn,
            ack: self.recv_next,
            flags: flags::SYN | flags::ACK,
            window: DEFAULT_WINDOW,
            payload: Vec::new(),
        };

        // Record the SYN-ACK for retransmission.
        self.retransmit_queue.push(RetransmitEntry {
            seq_start: isn,
            seq_end: isn.wrapping_add(1),
            segment: seg.clone(),
            first_sent_at: now,
            last_sent_at: now,
            retransmit_count: 0,
        });

        Ok(seg)
    }

    // ── Segment processing ────────────────────────────────────────

    /// Process an incoming TCP segment.
    ///
    /// Returns an optional outgoing segment (e.g. ACK) to be sent.
    /// The `now` timestamp is used for RTT measurement and timer management.
    pub fn on_segment(&mut self, seg: &TcpPacket<&[u8]>, now: Instant) -> Result<Option<TcpSegmentOut>> {
        match self.state {
            TcpState::SynSent => self.on_segment_syn_sent(seg, now),
            TcpState::SynReceived => self.on_segment_syn_received(seg, now),
            TcpState::Established => self.on_segment_established(seg, now),
            TcpState::FinWait1 => self.on_segment_fin_wait1(seg, now),
            TcpState::FinWait2 => self.on_segment_fin_wait2(seg),
            TcpState::CloseWait => Ok(None), // waiting for local close
            TcpState::LastAck => self.on_segment_last_ack(seg, now),
            TcpState::Closing => self.on_segment_closing(seg),
            TcpState::TimeWait => Ok(None),
            _ => Err(NetError::InvalidState),
        }
    }

    /// Handle segment received in SYN-SENT state (client waiting for SYN-ACK).
    fn on_segment_syn_sent(&mut self, seg: &TcpPacket<&[u8]>, now: Instant) -> Result<Option<TcpSegmentOut>> {
        if seg.rst() {
            self.state = TcpState::Closed;
            self.retransmit_queue = RetransmitQueue::new();
            return Err(NetError::ConnectionRefused);
        }

        if seg.syn() && seg.ack() {
            // Verify ACK acknowledges our SYN
            if seg.ack_number() != self.send_next {
                return Err(NetError::InvalidHeader);
            }
            self.recv_isn = seg.seq_number();
            self.recv_next = seg.seq_number().wrapping_add(1);
            self.process_ack(seg.ack_number(), now);
            self.transition(TcpState::Established)?;

            // Send ACK to complete handshake
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_next,
                ack: self.recv_next,
                flags: flags::ACK,
                window: DEFAULT_WINDOW,
                payload: Vec::new(),
            }));
        }

        // Simultaneous open: received SYN (no ACK)
        if seg.syn() {
            self.recv_isn = seg.seq_number();
            self.recv_next = seg.seq_number().wrapping_add(1);
            self.transition(TcpState::SynReceived)?;
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_isn,
                ack: self.recv_next,
                flags: flags::SYN | flags::ACK,
                window: DEFAULT_WINDOW,
                payload: Vec::new(),
            }));
        }

        Ok(None)
    }

    /// Handle segment received in SYN-RECEIVED state (server waiting for ACK).
    fn on_segment_syn_received(&mut self, seg: &TcpPacket<&[u8]>, now: Instant) -> Result<Option<TcpSegmentOut>> {
        if seg.rst() {
            self.state = TcpState::Closed;
            self.retransmit_queue = RetransmitQueue::new();
            return Err(NetError::ConnectionReset);
        }

        if seg.ack() {
            if seg.ack_number() != self.send_next {
                return Err(NetError::InvalidHeader);
            }
            self.process_ack(seg.ack_number(), now);
            self.transition(TcpState::Established)?;
            return Ok(None);
        }

        Ok(None)
    }

    /// Handle segment received in ESTABLISHED state.
    fn on_segment_established(&mut self, seg: &TcpPacket<&[u8]>, now: Instant) -> Result<Option<TcpSegmentOut>> {
        if seg.rst() {
            self.state = TcpState::Closed;
            self.retransmit_queue = RetransmitQueue::new();
            return Err(NetError::ConnectionReset);
        }

        // Process ACK: advance send_una, drain retransmit queue, feed RTT
        if seg.ack() {
            let ack = seg.ack_number();
            if wrapping_gte(ack, self.send_una) && wrapping_lte(ack, self.send_next) {
                self.process_ack(ack, now);
            }
        }

        // Process incoming data
        let payload = seg.payload();
        if !payload.is_empty() {
            if seg.seq_number() == self.recv_next {
                for &byte in payload {
                    let _ = self.recv_buffer.push(byte);
                }
                self.recv_next = self.recv_next.wrapping_add(payload.len() as u32);
            }
            // Send ACK for received data
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_next,
                ack: self.recv_next,
                flags: flags::ACK,
                window: self.recv_buffer.available() as u16,
                payload: Vec::new(),
            }));
        }

        // Process FIN (remote initiated close)
        if seg.fin() {
            self.recv_next = self.recv_next.wrapping_add(1);
            self.transition(TcpState::CloseWait)?;
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_next,
                ack: self.recv_next,
                flags: flags::ACK,
                window: DEFAULT_WINDOW,
                payload: Vec::new(),
            }));
        }

        Ok(None)
    }

    fn on_segment_fin_wait1(&mut self, seg: &TcpPacket<&[u8]>, now: Instant) -> Result<Option<TcpSegmentOut>> {
        if seg.ack() && seg.fin() {
            // Simultaneous close
            self.recv_next = self.recv_next.wrapping_add(1);
            self.process_ack(seg.ack_number(), now);
            self.transition(TcpState::TimeWait)?;
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_next,
                ack: self.recv_next,
                flags: flags::ACK,
                window: DEFAULT_WINDOW,
                payload: Vec::new(),
            }));
        }
        if seg.ack() {
            self.process_ack(seg.ack_number(), now);
            self.transition(TcpState::FinWait2)?;
            return Ok(None);
        }
        if seg.fin() {
            self.recv_next = self.recv_next.wrapping_add(1);
            self.transition(TcpState::Closing)?;
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_next,
                ack: self.recv_next,
                flags: flags::ACK,
                window: DEFAULT_WINDOW,
                payload: Vec::new(),
            }));
        }
        Ok(None)
    }

    fn on_segment_fin_wait2(&mut self, seg: &TcpPacket<&[u8]>) -> Result<Option<TcpSegmentOut>> {
        if seg.fin() {
            self.recv_next = self.recv_next.wrapping_add(1);
            self.transition(TcpState::TimeWait)?;
            return Ok(Some(TcpSegmentOut {
                src_port: self.id.local_port,
                dst_port: self.id.remote_port,
                seq: self.send_next,
                ack: self.recv_next,
                flags: flags::ACK,
                window: DEFAULT_WINDOW,
                payload: Vec::new(),
            }));
        }
        Ok(None)
    }

    fn on_segment_last_ack(&mut self, seg: &TcpPacket<&[u8]>, now: Instant) -> Result<Option<TcpSegmentOut>> {
        if seg.ack() {
            self.process_ack(seg.ack_number(), now);
            self.transition(TcpState::Closed)?;
        }
        Ok(None)
    }

    fn on_segment_closing(&mut self, seg: &TcpPacket<&[u8]>) -> Result<Option<TcpSegmentOut>> {
        if seg.ack() {
            self.transition(TcpState::TimeWait)?;
        }
        Ok(None)
    }

    // ── Active close ──────────────────────────────────────────────

    /// Initiate an active close by sending a FIN.
    ///
    /// The `now` timestamp starts the retransmission timer for the FIN.
    pub fn close(&mut self, now: Instant) -> Result<TcpSegmentOut> {
        let next_state = match self.state {
            TcpState::Established => TcpState::FinWait1,
            TcpState::CloseWait => TcpState::LastAck,
            _ => return Err(NetError::InvalidState),
        };
        self.transition(next_state)?;
        let seq = self.send_next;
        let seg = TcpSegmentOut {
            src_port: self.id.local_port,
            dst_port: self.id.remote_port,
            seq,
            ack: self.recv_next,
            flags: flags::FIN | flags::ACK,
            window: DEFAULT_WINDOW,
            payload: Vec::new(),
        };
        self.send_next = self.send_next.wrapping_add(1); // FIN consumes a seq num

        // Record the FIN for retransmission.
        self.retransmit_queue.push(RetransmitEntry {
            seq_start: seq,
            seq_end: seq.wrapping_add(1),
            segment: seg.clone(),
            first_sent_at: now,
            last_sent_at: now,
            retransmit_count: 0,
        });

        Ok(seg)
    }

    // ── Data transfer ─────────────────────────────────────────────

    /// Queue application data for sending.
    ///
    /// Returns the number of bytes actually queued.
    pub fn send(&mut self, data: &[u8]) -> Result<usize> {
        if !self.state.can_send() {
            return Err(NetError::InvalidState);
        }
        let mut count = 0;
        for &byte in data {
            match self.send_buffer.push(byte) {
                Ok(()) => count += 1,
                Err(_) => break,
            }
        }
        Ok(count)
    }

    /// Read received data from the receive buffer.
    ///
    /// Returns the number of bytes read.
    pub fn receive(&mut self, buf: &mut [u8]) -> Result<usize> {
        if !self.state.can_recv() && self.recv_buffer.is_empty() {
            return Err(NetError::InvalidState);
        }
        let mut count = 0;
        for slot in buf.iter_mut() {
            match self.recv_buffer.pop() {
                Ok(byte) => {
                    *slot = byte;
                    count += 1;
                }
                Err(_) => break,
            }
        }
        Ok(count)
    }

    /// Flush queued send data into a segment.
    ///
    /// Returns `None` if there is no data to send.
    /// The `now` timestamp is recorded for retransmission timing.
    pub fn flush_send(&mut self, now: Instant) -> Option<TcpSegmentOut> {
        if self.send_buffer.is_empty() || !self.state.can_send() {
            return None;
        }

        let mut payload = Vec::new();
        while let Ok(byte) = self.send_buffer.pop() {
            payload.push(byte);
            if payload.len() >= 1460 {
                break; // MSS limit
            }
        }

        let seq = self.send_next;
        let payload_len = payload.len() as u32;
        self.send_next = self.send_next.wrapping_add(payload_len);

        let seg = TcpSegmentOut {
            src_port: self.id.local_port,
            dst_port: self.id.remote_port,
            seq,
            ack: self.recv_next,
            flags: flags::ACK | flags::PSH,
            window: self.recv_buffer.available() as u16,
            payload,
        };

        // Record for retransmission.
        self.retransmit_queue.push(RetransmitEntry {
            seq_start: seq,
            seq_end: seq.wrapping_add(payload_len),
            segment: seg.clone(),
            first_sent_at: now,
            last_sent_at: now,
            retransmit_count: 0,
        });

        Some(seg)
    }

    // ── Retransmission ────────────────────────────────────────────

    /// Process an ACK: advance `send_una`, drain the retransmit queue,
    /// and feed RTT samples into the RTO estimator.
    fn process_ack(&mut self, ack: u32, now: Instant) {
        self.send_una = ack;
        if let Some(rtt) = self.retransmit_queue.ack_up_to(ack, now) {
            self.rto.on_rtt_sample(rtt);
        }
    }

    /// Poll for retransmissions.
    ///
    /// Call this periodically (at least as often as `next_retransmit_at()`
    /// indicates). Returns segments that need to be resent.
    ///
    /// Returns `Err(NetError::TimedOut)` if a segment has exceeded the
    /// maximum number of retransmission attempts.
    pub fn poll_retransmit(&mut self, now: Instant) -> Result<Vec<TcpSegmentOut>> {
        let rto = self.rto.backed_off_rto();
        match self.retransmit_queue.collect_expired(now, rto) {
            RetransmitResult::NothingToDo => Ok(Vec::new()),
            RetransmitResult::Segments(segs) => {
                // Apply exponential backoff for the next attempt
                self.rto.backoff();
                Ok(segs)
            }
            RetransmitResult::Exhausted => {
                self.state = TcpState::Closed;
                self.retransmit_queue = RetransmitQueue::new();
                Err(NetError::TimedOut)
            }
        }
    }

    /// Returns the `Instant` at which `poll_retransmit` should next be called,
    /// or `None` if there are no in-flight segments.
    pub fn next_retransmit_at(&self) -> Option<Instant> {
        self.retransmit_queue.next_timeout(self.rto.backed_off_rto())
    }

    /// Returns `true` if the retransmit queue has no in-flight segments.
    pub fn retransmit_queue_empty(&self) -> bool {
        self.retransmit_queue.is_empty()
    }
}

/// Wrapping comparison: `a >= b` in sequence-number space.
fn wrapping_gte(a: u32, b: u32) -> bool {
    (a.wrapping_sub(b) as i32) >= 0
}

/// Wrapping comparison: `a <= b` in sequence-number space.
fn wrapping_lte(a: u32, b: u32) -> bool {
    (b.wrapping_sub(a) as i32) >= 0
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::time::Instant;

    fn client_id() -> ConnectionId {
        ConnectionId {
            local_addr: [10, 0, 0, 1],
            local_port: 50000,
            remote_addr: [10, 0, 0, 2],
            remote_port: 80,
        }
    }

    fn server_id() -> ConnectionId {
        ConnectionId {
            local_addr: [10, 0, 0, 2],
            local_port: 80,
            remote_addr: [10, 0, 0, 1],
            remote_port: 50000,
        }
    }

    /// Build a TCP segment from a TcpSegmentOut for testing.
    fn seg_to_bytes(seg: &TcpSegmentOut, src_addr: &[u8; 4], dst_addr: &[u8; 4]) -> Vec<u8> {
        let mut buf = vec![0u8; 20 + seg.payload.len()];
        tcp::build_tcp(
            &mut buf,
            seg.src_port,
            seg.dst_port,
            seg.seq,
            seg.ack,
            seg.flags,
            seg.window,
            &seg.payload,
            src_addr,
            dst_addr,
        )
        .unwrap();
        buf
    }

    /// Helper: perform a full three-way handshake and return (client, server).
    fn establish_pair() -> (TcpConnection, TcpConnection) {
        let mut client = TcpConnection::with_capacity(client_id(), 1024);
        let mut server = TcpConnection::with_capacity(server_id(), 1024);
        let t0 = Instant::from_millis(0);
        let t1 = Instant::from_millis(10);
        let t2 = Instant::from_millis(20);
        let t3 = Instant::from_millis(30);

        server.listen().unwrap();
        let syn_out = client.connect(1000, t0).unwrap();
        let syn_bytes = seg_to_bytes(&syn_out, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let syn_pkt = TcpPacket::new(&syn_bytes[..]).unwrap();
        let syn_ack_out = server.accept(&syn_pkt, 2000, t1).unwrap();
        let syn_ack_bytes = seg_to_bytes(&syn_ack_out, &[10, 0, 0, 2], &[10, 0, 0, 1]);
        let syn_ack_pkt = TcpPacket::new(&syn_ack_bytes[..]).unwrap();
        let ack_out = client.on_segment(&syn_ack_pkt, t2).unwrap().unwrap();
        let ack_bytes = seg_to_bytes(&ack_out, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let ack_pkt = TcpPacket::new(&ack_bytes[..]).unwrap();
        server.on_segment(&ack_pkt, t3).unwrap();

        assert_eq!(client.state(), TcpState::Established);
        assert_eq!(server.state(), TcpState::Established);
        (client, server)
    }

    #[test]
    fn test_three_way_handshake() {
        let mut client = TcpConnection::with_capacity(client_id(), 1024);
        let mut server = TcpConnection::with_capacity(server_id(), 1024);
        let t = Instant::from_millis(0);

        // Server: passive open
        server.listen().unwrap();
        assert_eq!(server.state(), TcpState::Listen);

        // Client: active open → SYN
        let syn_out = client.connect(1000, t).unwrap();
        assert_eq!(client.state(), TcpState::SynSent);
        assert_eq!(syn_out.flags, flags::SYN);
        assert_eq!(syn_out.seq, 1000);

        // Server receives SYN → SYN-ACK
        let syn_bytes = seg_to_bytes(&syn_out, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let syn_pkt = TcpPacket::new(&syn_bytes[..]).unwrap();
        let syn_ack_out = server.accept(&syn_pkt, 2000, t).unwrap();
        assert_eq!(server.state(), TcpState::SynReceived);
        assert_eq!(syn_ack_out.flags, flags::SYN | flags::ACK);
        assert_eq!(syn_ack_out.seq, 2000);
        assert_eq!(syn_ack_out.ack, 1001);

        // Client receives SYN-ACK → ACK
        let syn_ack_bytes = seg_to_bytes(&syn_ack_out, &[10, 0, 0, 2], &[10, 0, 0, 1]);
        let syn_ack_pkt = TcpPacket::new(&syn_ack_bytes[..]).unwrap();
        let ack_out = client.on_segment(&syn_ack_pkt, t).unwrap().unwrap();
        assert_eq!(client.state(), TcpState::Established);
        assert_eq!(ack_out.flags, flags::ACK);

        // Server receives ACK → ESTABLISHED
        let ack_bytes = seg_to_bytes(&ack_out, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let ack_pkt = TcpPacket::new(&ack_bytes[..]).unwrap();
        let response = server.on_segment(&ack_pkt, t).unwrap();
        assert!(response.is_none()); // no segment to send
        assert_eq!(server.state(), TcpState::Established);
    }

    #[test]
    fn test_data_transfer() {
        let (mut client, mut server) = establish_pair();
        let t = Instant::from_millis(100);

        // Client sends data
        let msg = b"Hello, server!";
        let n = client.send(msg).unwrap();
        assert_eq!(n, msg.len());
        let data_seg = client.flush_send(t).unwrap();
        assert_eq!(data_seg.payload, msg);

        // Server receives data
        let data_bytes = seg_to_bytes(&data_seg, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let data_pkt = TcpPacket::new(&data_bytes[..]).unwrap();
        let ack_resp = server.on_segment(&data_pkt, t).unwrap().unwrap();
        assert_eq!(ack_resp.flags, flags::ACK);

        // Server reads data
        let mut recv_buf = [0u8; 64];
        let n = server.receive(&mut recv_buf).unwrap();
        assert_eq!(&recv_buf[..n], msg);
    }

    #[test]
    fn test_connection_close() {
        let (mut client, mut server) = establish_pair();
        let t = Instant::from_millis(100);

        // Client initiates close → FIN
        let fin_out = client.close(t).unwrap();
        assert_eq!(client.state(), TcpState::FinWait1);
        assert!(fin_out.flags & flags::FIN != 0);

        // Server receives FIN → CloseWait, sends ACK
        let fin_bytes = seg_to_bytes(&fin_out, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let fin_pkt = TcpPacket::new(&fin_bytes[..]).unwrap();
        let ack_resp = server.on_segment(&fin_pkt, t).unwrap().unwrap();
        assert_eq!(server.state(), TcpState::CloseWait);

        // Client receives ACK → FinWait2
        let ack_bytes2 = seg_to_bytes(&ack_resp, &[10, 0, 0, 2], &[10, 0, 0, 1]);
        let ack_pkt2 = TcpPacket::new(&ack_bytes2[..]).unwrap();
        client.on_segment(&ack_pkt2, t).unwrap();
        assert_eq!(client.state(), TcpState::FinWait2);

        // Server closes → FIN
        let server_fin = server.close(t).unwrap();
        assert_eq!(server.state(), TcpState::LastAck);

        // Client receives FIN → TimeWait
        let sfin_bytes = seg_to_bytes(&server_fin, &[10, 0, 0, 2], &[10, 0, 0, 1]);
        let sfin_pkt = TcpPacket::new(&sfin_bytes[..]).unwrap();
        let final_ack = client.on_segment(&sfin_pkt, t).unwrap().unwrap();
        assert_eq!(client.state(), TcpState::TimeWait);

        // Server receives final ACK → Closed
        let fack_bytes = seg_to_bytes(&final_ack, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let fack_pkt = TcpPacket::new(&fack_bytes[..]).unwrap();
        server.on_segment(&fack_pkt, t).unwrap();
        assert_eq!(server.state(), TcpState::Closed);
    }

    #[test]
    fn test_send_in_wrong_state() {
        let mut conn = TcpConnection::new(client_id());
        assert_eq!(conn.send(b"data"), Err(NetError::InvalidState));
    }

    // ── Retransmission tests ─────────────────────────────────────

    #[test]
    fn test_retransmit_syn() {
        let mut client = TcpConnection::with_capacity(client_id(), 1024);
        let t0 = Instant::from_millis(0);

        let syn_out = client.connect(1000, t0).unwrap();
        assert!(!client.retransmit_queue_empty());

        // Before timeout → nothing to retransmit
        let t_early = Instant::from_millis(500);
        let segs = client.poll_retransmit(t_early).unwrap();
        assert!(segs.is_empty());

        // At timeout (initial RTO = 1000 ms) → SYN retransmitted
        let t_rto = Instant::from_millis(1000);
        let segs = client.poll_retransmit(t_rto).unwrap();
        assert_eq!(segs.len(), 1);
        assert_eq!(segs[0].seq, syn_out.seq);
        assert_eq!(segs[0].flags, flags::SYN);
    }

    #[test]
    fn test_retransmit_data_segment() {
        let (mut client, _server) = establish_pair();
        let t_send = Instant::from_millis(100);

        // Send data
        client.send(b"test data").unwrap();
        let data_seg = client.flush_send(t_send).unwrap();
        assert!(!client.retransmit_queue_empty());

        // RTO is initially 1000ms; after handshake RTT samples it may
        // have been updated, but let's check at a safe time well past RTO.
        let t_timeout = Instant::from_millis(2000);
        let segs = client.poll_retransmit(t_timeout).unwrap();
        assert_eq!(segs.len(), 1);
        assert_eq!(segs[0].seq, data_seg.seq);
        assert_eq!(segs[0].payload, b"test data");
    }

    #[test]
    fn test_ack_clears_retransmit_queue() {
        let (mut client, mut server) = establish_pair();
        let t = Instant::from_millis(100);

        // Send data and get ACK
        client.send(b"acked data").unwrap();
        let data_seg = client.flush_send(t).unwrap();
        assert!(!client.retransmit_queue_empty());

        // Server receives and ACKs
        let data_bytes = seg_to_bytes(&data_seg, &[10, 0, 0, 1], &[10, 0, 0, 2]);
        let data_pkt = TcpPacket::new(&data_bytes[..]).unwrap();
        let ack_out = server.on_segment(&data_pkt, t).unwrap().unwrap();

        // Client processes the ACK
        let ack_bytes = seg_to_bytes(&ack_out, &[10, 0, 0, 2], &[10, 0, 0, 1]);
        let ack_pkt = TcpPacket::new(&ack_bytes[..]).unwrap();
        let t_ack = Instant::from_millis(120);
        client.on_segment(&ack_pkt, t_ack).unwrap();

        // Retransmit queue should be empty
        assert!(client.retransmit_queue_empty());
    }

    #[test]
    fn test_retransmit_backoff() {
        let mut client = TcpConnection::with_capacity(client_id(), 1024);
        let t0 = Instant::from_millis(0);
        client.connect(1000, t0).unwrap();

        // First RTO fires at t=1000, backed_off_rto doubles to 2000
        let segs = client.poll_retransmit(Instant::from_millis(1000)).unwrap();
        assert_eq!(segs.len(), 1);

        // Second RTO should NOT fire at t=2000 (need 1000 + 2000 = 3000 from last_sent_at=1000)
        let segs = client.poll_retransmit(Instant::from_millis(2000)).unwrap();
        assert!(segs.is_empty());

        // Second RTO fires at t=3000
        let segs = client.poll_retransmit(Instant::from_millis(3000)).unwrap();
        assert_eq!(segs.len(), 1);
    }

    #[test]
    fn test_next_retransmit_at() {
        let mut client = TcpConnection::with_capacity(client_id(), 1024);
        let t0 = Instant::from_millis(0);

        // No outstanding segments → None
        assert!(client.next_retransmit_at().is_none());

        client.connect(1000, t0).unwrap();
        // Initial RTO = 1000ms, sent at t=0 → next retransmit at t=1000
        assert_eq!(client.next_retransmit_at(), Some(Instant::from_millis(1000)));
    }
}
